if (!Application.isPlaying) return "Play Mode required";
var cameraObject = new GameObject("Perch audit camera");
var camera=cameraObject.AddComponent<Camera>(); camera.enabled=false;camera.orthographic=true;camera.orthographicSize=2.6f;
camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.18f,.23f,.19f);
var perch=GameObject.Find("Bird perch").transform;
var tree=perch.parent;
Vector3 focus=tree.position+Vector3.up*1.65f;
camera.transform.position=focus+new Vector3(1.3f,.4f,-3)*3;camera.transform.LookAt(focus);
var rt=new RenderTexture(900,900,24);camera.targetTexture=rt;
var previous=RenderTexture.active;
camera.Render();RenderTexture.active=rt;
var png=new Texture2D(900,900,TextureFormat.RGB24,false);png.ReadPixels(new Rect(0,0,900,900),0,0);png.Apply();
System.IO.File.WriteAllBytes("Artifacts/motion-audit/perch.png",png.EncodeToPNG());
RenderTexture.active=previous;camera.targetTexture=null;
UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(png);UnityEngine.Object.DestroyImmediate(cameraObject);
return "Captured branch attachment";
