if (Application.isPlaying) throw new System.InvalidOperationException("Stop Play Mode first.");
var settings = AssetDatabase.LoadAssetAtPath<GardenSnake.SnakeMouthSettings>("Assets/GardenSnake/Tuning/Snake Mouth.asset");
var bound = new SerializedObject(settings);
bound.FindProperty("anticipationDistance").floatValue = 3.2f;
bound.FindProperty("anticipationRamp").floatValue = 1.7f;
bound.FindProperty("upperFaceLift").floatValue = .65f;
bound.FindProperty("cavityOpeningOffset").vector3Value = new Vector3(0, .385f, .12f);
bound.FindProperty("cavityOpeningScale").vector3Value = new Vector3(1.32f, .923f, .715f);
bound.FindProperty("jawOpeningOffset").vector3Value = new Vector3(0, .04f, .32f);
bound.FindProperty("jawOpeningScale").vector3Value = new Vector3(1.12f, .1f, .53f);
bound.FindProperty("tongueOpeningOffset").vector3Value = new Vector3(0, .06f, .29f);
bound.ApplyModifiedPropertiesWithoutUndo();
EditorUtility.SetDirty(settings);
AssetDatabase.SaveAssetIfDirty(settings);
return "Exaggerated mouth anticipation and eye tuning saved.";
