if (Application.isPlaying) throw new System.InvalidOperationException("Stop Play Mode first.");
var scene = UnityEngine.SceneManagement.SceneManager.GetActiveScene();
if (scene.isDirty) throw new System.InvalidOperationException("Unexpected unsaved scene edits.");
var c = UnityEngine.Object.FindFirstObjectByType<GardenSnake.SnakeController>();
var waves = UnityEngine.Object.FindFirstObjectByType<GardenSnake.GridCellWaves>();
var controllerFields = new SerializedObject(c);
var skin = (GardenSnake.SnakeSkinSettings)controllerFields.FindProperty("skinSettings").objectReferenceValue;
SessionState.SetString("TuningVariant.Controller", EditorJsonUtility.ToJson(c));
SessionState.SetString("TuningVariant.Waves", EditorJsonUtility.ToJson(waves));
SessionState.SetString("TuningVariant.Skin", EditorJsonUtility.ToJson(skin));
controllerFields.FindProperty("initialLength").intValue = 2;
controllerFields.FindProperty("turnBufferSize").intValue = 3;
controllerFields.FindProperty("firstAppleDistance").intValue = 3;
controllerFields.ApplyModifiedPropertiesWithoutUndo();
var waveFields = new SerializedObject(waves);
waveFields.FindProperty("maximumConcurrentWaves").intValue = 3;
waveFields.ApplyModifiedPropertiesWithoutUndo();
var skinFields = new SerializedObject(skin);
skinFields.FindProperty("sides").intValue = 8;
skinFields.FindProperty("samplesPerCell").intValue = 3;
skinFields.ApplyModifiedPropertiesWithoutUndo();
return "Temporary startup variant configured; run Play Mode verification, then tuning_variant_restore.cs. No scene/asset saved.";
